### ISSUE TITLE
Editor MVP

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#10]
On the day we launch, nobody is going to come to mytake.org to read, because there won't be anything to read.  The cornerstone assumption in our growth model is that users will enjoy an editing experience that makes it easy to cite primary sources.

If a user writes a take, posts it to facebook, and people read it, that is not enough.  **We need readers to become repeat writers.**  We need readers to have a big "give us your take" button, and when they click it they need to get sucked into the experience of browsing primary sources and then using them to build their case.

We can build and iterate on the editing experience without doing any serverside work at all.  I've setup a template where we can look at mockups for this.  Whatever we put in the `/docs` folder of this repo will get published to these URLs:

- [homepage / newsfeed](https://nedtwigg.github.io/mytake/)
- [about us (our pitch to new users)](https://nedtwigg.github.io/mytake/about/)
- [new take (MVP for the editor experience)](https://nedtwigg.github.io/mytake/editor/)

Here's an example of the medium editor in action:
![mediumexample](https://cloud.githubusercontent.com/assets/2924992/22624152/59dc99a8-eb27-11e6-8eb1-ae7df49024a0.gif)

When the user presses the "+", we need an engaging set of cards to pop up.  We want to draw the user into our Foundation of evidence, and make it easy and fun to browse.  Here's just one idea (could be lots of others):

1. Top level menu is a card for Laws and a card for Speeches
2. For each thing you pick, a timeline pops up.
    + Laws timeline is Declaration of Independence, Articles of Confederation, Constitution, Amendments
    + Speeches is timeline from present to however far back we have for debates.

Regardless of how we decide to present the evidence, one of our key implementation choices will be the UI components that we pick.

## Rich text

There are tons of rich text editors, but I was only able to find a few that match Medium's minimalist style:

- [medium-editor-insert-plugin](https://github.com/orthes/medium-editor-insert-plugin), [demo](http://orthes.github.io/medium-editor-insert-plugin) (889 stars, last commit 6mo)
- [dante](https://github.com/michelson/Dante), [demo](http://michelson.github.io/Dante/) (1399 stars, last commit 2mo)

Both run fast enough on mobile, but look terrible because they're way too big.  I think it's just a CSS bug that we could fix.

FWIW, Medium has apps for mobile, but refuses to run in mobile browsers.  I think apps are totally out of our budget, and we should focus on a single responsive web app from desktop to mobile.

## Timeline

This is optional, but there are some really cool timeline widgets out there.

- [knightlab](http://timeline.knightlab.com/)
- [visjs](http://visjs.org/timeline_examples.html)
- [vertical timeline](https://webdesign.tutsplus.com/tutorials/building-a-vertical-timeline-with-css-and-a-touch-of-javascript--cms-26528)

@WebsByTodd, assuming we take this route, this is probably gonna end up being your job, so your opinion on all this stuff is probably the most important :)

**Comment by hattersv** [comment]
I don't have evidence but I get the sense that people are interested in actually reading the constitution, so this 'tool' (what do we actually call it?) has an additional attraction of offering the opportunity to get much more familiar with it and other such documents.  I can even see an educational use for it in schools.

**Comment by hattersv** [comment]
Are the Federalist Papers on the list as well?

**Comment by nedtwigg** [comment]
> Are the Federalist Papers on the list as well?

This is a fantastic idea.  This issue is focused on the technical issue of building the editor, independent of what sources to include.  [This](https://github.com/nedtwigg/mytake/issues/2) is the issue where we're discussing what to include / exclude.

> I can even see an educational use for it in schools.

Absolutely!  Writing an essay with citations is a classic gradeschool activity.  We can make it easier to achieve that level of rigor.

**Comment by nedtwigg** [comment]
Todd will start putting the skeleton of our editor together later this week.

We're going to prioritize work kanban-style [here](https://github.com/nedtwigg/mytake/projects/3). 

If you haven't worked with Kanban before, here's the gist.  The kanban board isn't for discussing strategy or high-level goals - it's the place where bitesized pieces of actual work (e.g. fixing a bug or adding a feature) gets prioritized and tracked.

- **Inbox** - all work items start here.  If you find a bug in the editor or have an idea you'd like to get added, create an issue and put it here.
- **Backlog** - this is a work item that we've decided to actually build, prioritized with the most important thing at the top.
- **In Progress** - once we start to actually build something, it goes here.
- **Done** - this is where work goes when it has been completed.

**Comment by WebsByTodd** [comment]
Making progress, closing issues for now that don't directly impact tasks to be done or code.
