### ISSUE TITLE
Take editor first cut

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#18]
A title at the top
Insert a paragraph of plaintext
Insert a piece of evidence
Insert a paragraph of plaintext
Insert a piece of evidence

Just a super super simple block-based text editor.  The "evidence" could just be `<div class="constitution"></div>` and `<div class="debate"></div>`.

No need for bold, italic, etc.  Just simple.

Might be some useful example code in the react example here:
https://github.com/gothinkster/realworld

**Comment by nedtwigg** [comment]
This is at the top of hackernews right now:
https://github.com/ory/editor
https://news.ycombinator.com/item?id=14417340

It's based on this:
https://github.com/ianstormtaylor/slate

Just a thought :)

**Comment by WebsByTodd** [comment]
Used Slate for now. Will open a new issue for future strategy.

https://github.com/nedtwigg/mytake/commit/242a2775d92333af52068e91928fa628a12ba019
