### ISSUE TITLE
Debate embed first cut

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#19]
For the first cut, we'll only support the debates which are on Youtube.

(For now, looks like it's just Jimmy Carter and Gerald Ford, plenty good enough to start with)
https://github.com/nedtwigg/mytake/wiki/Video-Facts

User should be guided through the available debates, and be able to embed the section of their choosing into their take.

**Comment by WebsByTodd** [comment]
UI needs to be overhauled, but first cut is complete. #44
