### ISSUE TITLE
Addiction

### ISSUE THREAD

**Issue by WebsByTodd** [nedtwigg/mytake#23]
A Google search of  "what makes an app addictive" yields many results. Although our goal isn't revenue beyond sustainability, it is to get people to use and to continue to use our platform. With that in mind I think we need to give it every chance of success.

- A simple interface.
- Bug free.
- No loading without fun animations, trivia, or distractions.
- Flawless on-boarding process for new users.
- Allow user control over colors, layouts, settings, etc.
- Timers (not sure how to implement this yet, but it is VERY effective)
  - Can only progress to level 2 in 30/60/90 minutes.
  - After 30/60/90 minutes, must return to `fill-in-the-blank` or lose all progress.
- Encourage time shortcuts.
  - Share to speed up timer.
  - Leave feedback to speed up timer.
- Notifications.
  - Always have a positive impact.
  - Reward returning users with constant innovation, growth, improvement. (level 2, ability to customize color, etc.)
- Engage subconscious mind.
  - Use color.
  - Use sweet tasting food imagery. (maybe not for us, but it's effective)
  - Place portraits on red backgrounds.
  - Connect app components/processes to positive experiences (i.e. the way it feels to open a can of soda or connect the power cord to a macbook pro).
- The loop.
  - Offer a challenge that requires action, e.g.:
    - Get 1 retweet (or 2 or 10)  on your take.
    - Use three Facts from the Foundation in a take.
  - Reward completed action. (timer shortcuts, level 2, extra abilities)
  - Repeat.
- Organize patterns and shapes (jigsaw puzzle interface?)
- User scores/rankings/pride

I think the hardest part of this process is defining what to do. Most of these new "features" should be relatively easy to implement from a technical standpoint. Thoughts?

See [10 ingredients concoct subconsciously addictive mobile app](https://thenextweb.com/dd/2014/10/28/10-ingredients-concoct-subconsciously-addictive-mobile-app)

**Comment by nedtwigg** [comment]
Great summary.  We should definitely keep the engagement loop in mind as we polish.

IMO, these are all micro-optimizations compared to video evidence.

**Comment by WebsByTodd** [comment]
Closing this since there's nothing actionable. Will certainly keep it in mind.
