### ISSUE TITLE
Presentation July 12th

### ISSUE THREAD

**Issue by WebsByTodd** [nedtwigg/mytake#24]
On July 12th I'll be presenting the mytake idea and initial prototype to the Grand Strand Technology Council in Myrtle Beach, SC. [More event info here](http://gstechcouncil.org/event/entrepreneurial-explorers-5/?instance_id=187).

The purpose is to get early feedback, judge the general reaction to the concept, and to find more people willing to donate time, money, or expertise to the project.

The audience typically consists of about 20 local entrepreneurs with an interest in technology.

Would it be possible before the week of the 12th to:

1.  Have a copywriter refine our elevator pitch?
2.  Have a list of frequently asked questions about mytake and their answers?
3.  Have a take written using the text of the constitution?

I want to be prepared to make mytake look as awesome as possible. I will have the constitution portion of mytake ready before the 12th and I'll make it as visually appealing as I can. Not sure if I'll have the debates videos ready by then.

**Comment by hattersv** [comment]
Hi Todd-I have been working on trying to convert the 501C3 documents and have reworded some of the pitch  so could provide that if we identify a copy editor .    Dave is also pretty good at this stuff as he mentioned and he could take a crack at it.    I  could also work to draft the FAQ from an end user perspective,  but I'm not sure if that's useful at a technology conference.

**Comment by WebsByTodd** [comment]
That would be great, thank you! 

Even though it's the "technology" council, most of the attendees aren't nearly as techie as Ned and I are. At the last event I met a woman who owns an HR business and another woman who sells health insurance, so I will expect questions from an end-user perspective.

**Comment by hattersv** [comment]
Hi there -  Dave and I have done some work on the FAQ - considering what questions might be asked and have started answering them.  More work to be done but let us know if we are going in the right direction.  We worked in information from the Pitch as we could.  Please let us know how to proceed - e.g. if we should do more or if you want to take it from here.

[Frequently Asked Questions.docx](https://github.com/nedtwigg/mytake/files/1120460/Frequently.Asked.Questions.docx)

Next comment is on the elevator pitch

**Comment by hattersv** [comment]
Regarding the elevator speech - I spoke with Dave and he will do this tomorrow.  Can you please give him access to Github?  amatodave@gmail.com.

**Comment by WebsByTodd** [comment]
Thank you for putting this information together!! I created a new page on the wiki with the Frequently Asked Questions to make it easy to view online and to reference from other places. I believe you can edit the Wiki directly going forward. I look forward to reading the elevator pitch also.

Ned is the owner of the repository, so only he can give Dave access. I'm sure he'll do this as soon as he can.

I know this is a lot to pile on, but have you had an opportunity to try out the prototype with the Constitution? 

[https://nedtwigg.github.io/mytake/](https://nedtwigg.github.io/mytake/)

**Comment by nedtwigg** [comment]
I'm back!  I can't add Dave until he has a GitHub account - go to https://github.com and click "Sign up" in the top right.  Let me know when you've got an account and I can add you.

FAQ looks great!

I'll write an article or two.  If anyone else writes one they'd like to share, take a screenshot and copy-paste the text into a word document.  Todd or I can take them and build them as "presets" into the app so people can see example articles before we build out the full save/share functionality.

Initial prototype is fantastic!  Lots left to do, but you've solved some of the hard problems.

**Functional feedback:**
- Hard to start a new paragraph after an evidence block
    + Immediately start a new empty paragraph after inserting an evidence block?
    + Any click below an evidence block should start a new paragraph?
- Hard to delete an evidence block
    + Hover over an evidence block brings up a "delete" button?

**Style feedback:**
- Obviously, this draft is very early, so some of this feedback is probably premature.
- We want to show that the Constitution isn't a stuffy historical document, but rather a simple and relevant document.  I think our typography should speak to that, and the current typography makes it too antique-y.  I think we should axe the "yellow-paper" look for a neutral gray, and use a more modern and easy to read font.  I'm a fan of the [New Yorker's](http://www.newyorker.com/books/page-turner/this-week-in-fiction-hye-young-pyun-on-the-role-of-suspense-in-storytelling) font.
- We're going to get deluged in feedback over the misaligned title.  Even though we're focused on just the editor functionality, I think it's unavoidable to do an initial style over the entire page.  I think that ought to be a priority before the presentation.
- Even V1 has to look good on mobile - your audience will probably view it on their phones before their laptops, I'd imagine.

**Comment by hattersv** [comment]
Happy birthday USA!

Dave edited the Pitch document and he and I reviewed.  I attach the results.  I assume that the elevator speech is just the first part.  We'll need to be sure that the Q&A and the Pitch match.  Need to work on the other pieces, such as strategic, communications, and marketing plans.  Will look at the prototype, I did give it a quick try but wasn't exactly sure what I was supposed to do... will try again, and will encourage Dave to do his thing with github.

Hope that this helps with the presentation, good luck Todd and can't wait to hear how it goes!
[MytakeWikiPitchRevisedVH+DAA.docx](https://github.com/nedtwigg/mytake/files/1123271/MytakeWikiPitchRevisedVH.DAA.docx)

**Comment by hattersv** [comment]
Dave set up his Github account so you can add him now, thanks!

**Comment by WebsByTodd** [comment]
I copy/pasted your revised pitch into the Wiki [https://github.com/nedtwigg/mytake/wiki/Pitch](https://github.com/nedtwigg/mytake/wiki/Pitch).

I also added a [User Feedback Survey](https://github.com/nedtwigg/mytake/wiki/User-Feedback-Survey). I'll have physical copies of this for people to fill out next week. Eventually it will be added to the site as well so online users can leave feedback. 

Please feel free to suggest changes on this.

**Comment by WebsByTodd** [comment]
Event was a success. Closing this issue, but the conversation will continue elsewhere.
