### ISSUE TITLE
In-house paragraph implementation

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#33]
Looks like we can get by with a `textarea` and our own state management rather than the full-blown slate.

- [Why ContentEditable is Terrible](https://medium.engineering/why-contenteditable-is-terrible-122d8a40e480) is great.

**Comment by nedtwigg** [comment]
Remove debug stuff.

**Comment by WebsByTodd** [comment]
This is done. Will be in next PR.

**Comment by nedtwigg** [comment]
- [ ] Need to press down on every paragraph when opening a document

**Comment by WebsByTodd** [comment]
Fixed.
