### ISSUE TITLE
Misc cleanup from block editor

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#36]
- [x] Refactor selection logic either into BlockContainer or into shared functions that called by ParagraphBlockProps and DocumentBlockProps
- [x] Change id to idx for places where it is an idx
- [x] Remove hover
- [x] Refactor document state out of react and into functions

**Comment by WebsByTodd** [comment]
Changed ID to IDX, removed hover logic, refactored document state into common functions file.

Couldn't refactor much of selection logic into BlockContainer or shared functions due to event listener specifics on the underlying child elements. Possible future work here.
